#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace claim_tax
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hrdb")]
	public partial class DbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEMPLOYEE_INFO(EMPLOYEE_INFO instance);
    partial void UpdateEMPLOYEE_INFO(EMPLOYEE_INFO instance);
    partial void DeleteEMPLOYEE_INFO(EMPLOYEE_INFO instance);
    partial void InsertTAX_Desc(TAX_Desc instance);
    partial void UpdateTAX_Desc(TAX_Desc instance);
    partial void DeleteTAX_Desc(TAX_Desc instance);
    partial void InsertPA0364(PA0364 instance);
    partial void UpdatePA0364(PA0364 instance);
    partial void DeletePA0364(PA0364 instance);
    partial void InsertDB_New(DB_New instance);
    partial void UpdateDB_New(DB_New instance);
    partial void DeleteDB_New(DB_New instance);
    partial void InsertEMPLOYEE_LOGIN(EMPLOYEE_LOGIN instance);
    partial void UpdateEMPLOYEE_LOGIN(EMPLOYEE_LOGIN instance);
    partial void DeleteEMPLOYEE_LOGIN(EMPLOYEE_LOGIN instance);
    partial void InsertDB_FAQ(DB_FAQ instance);
    partial void UpdateDB_FAQ(DB_FAQ instance);
    partial void DeleteDB_FAQ(DB_FAQ instance);
    partial void InsertTaxEdit_List(TaxEdit_List instance);
    partial void UpdateTaxEdit_List(TaxEdit_List instance);
    partial void DeleteTaxEdit_List(TaxEdit_List instance);
    #endregion
		
		public DbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["hrdbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EMPLOYEE_INFO> EMPLOYEE_INFOs
		{
			get
			{
				return this.GetTable<EMPLOYEE_INFO>();
			}
		}
		
		public System.Data.Linq.Table<TAX_Desc> TAX_Descs
		{
			get
			{
				return this.GetTable<TAX_Desc>();
			}
		}
		
		public System.Data.Linq.Table<PA0364> PA0364s
		{
			get
			{
				return this.GetTable<PA0364>();
			}
		}
		
		public System.Data.Linq.Table<DB_New> DB_News
		{
			get
			{
				return this.GetTable<DB_New>();
			}
		}
		
		public System.Data.Linq.Table<EMPLOYEE_LOGIN> EMPLOYEE_LOGINs
		{
			get
			{
				return this.GetTable<EMPLOYEE_LOGIN>();
			}
		}
		
		public System.Data.Linq.Table<DB_FAQ> DB_FAQs
		{
			get
			{
				return this.GetTable<DB_FAQ>();
			}
		}
		
		public System.Data.Linq.Table<TaxEdit_List> TaxEdit_Lists
		{
			get
			{
				return this.GetTable<TaxEdit_List>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMPLOYEE_INFO")]
	public partial class EMPLOYEE_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _E_ID;
		
		private System.Nullable<decimal> _E_TITLE_TYPE;
		
		private System.Nullable<decimal> _E_TITLE;
		
		private string _E_TITLE_DESC;
		
		private string _E_TITLE_FULL_DESC;
		
		private string _E_TITLE1;
		
		private string _E_TITLE1_DESC;
		
		private string _E_TITLE2;
		
		private string _E_TITLE2_DESC;
		
		private string _E_TITLE3;
		
		private string _E_TITLE3_DESC;
		
		private string _E_TITLE4;
		
		private string _E_TITLE4_DESC;
		
		private string _E_NAMEF;
		
		private string _E_NAMEL;
		
		private System.Nullable<System.DateTime> _E_PERM_DATE;
		
		private System.Nullable<System.DateTime> _E_BIRTH_DATE;
		
		private System.Nullable<System.DateTime> _E_ENTRY_DATE;
		
		private string _E_POSI_ST;
		
		private string _E_POS_ST_DESC;
		
		private System.Nullable<System.DateTime> _E_POSI_DATE;
		
		private System.Nullable<System.DateTime> _E_STAFF_DATE;
		
		private string _E_RELIGION;
		
		private string _E_RELG_NAME;
		
		private string _E_RACE;
		
		private string _RACE_NAME;
		
		private string _E_NATIONALITY;
		
		private string _NATIONALITY_NAME;
		
		private string _E_MARITAL_ST;
		
		private string _E_MARITAL_ST_DESC;
		
		private string _E_SEX;
		
		private string _E_SEX_DESC;
		
		private string _E_POSI_CODE;
		
		private string _E_POST_TEXT_SHORT;
		
		private string _E_POST_TEXT;
		
		private string _E_LEVEL_CODE;
		
		private string _E_LEVEL_DESC;
		
		private string _DEPT_STABLE_CODE;
		
		private string _DEPT_CHANGE_CODE;
		
		private string _DEPT_SHORT;
		
		private string _DEPT_FULL;
		
		private System.Nullable<System.DateTime> _E_RETIRED;
		
		private string _E_EMP_ST;
		
		private string _E_EMP_ST_DESC;
		
		private System.Nullable<System.DateTime> _E_UPD_DATE;
		
		private System.Nullable<System.DateTime> _E_RETIRED2_DATE;
		
		private System.Nullable<decimal> _E_QUALIF;
		
		private string _E_QUALIF_DESC;
		
		private string _E_QUALIF_LEVEL;
		
		private string _E_QUALIF_LEVEL_DESC;
		
		private System.Nullable<decimal> _E_DEPT;
		
		private string _E_DEPT_DESC;
		
		private string _E_BLOOD_GROUP;
		
		private string _E_IDENTITY_NO;
		
		private string _E_DEPT_SAP;
		
		private string _E_DEPT_SHORT;
		
		private string _E_DEPT_FULL;
		
		private string _E_REG;
		
		private string _E_REG_NAME;
		
		private string _E_SUB_REG;
		
		private string _E_SUB_REG_NAME;
		
		private string _E_COST_CENTER;
		
		private string _E_COST_CENTER_NAME;
		
		private string _E_BA;
		
		private string _E_BA_NAME;
		
		private string _E_PY_AREA;
		
		private string _E_PY_AREA_NAME;
		
		private string _E_VENDOR_CODE;
		
		private System.Nullable<System.DateTime> _E_BEG_DATE;
		
		private System.Nullable<System.DateTime> _E_CONT_DATE;
		
		private System.Nullable<System.DateTime> _E_END_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_IDChanging(string value);
    partial void OnE_IDChanged();
    partial void OnE_TITLE_TYPEChanging(System.Nullable<decimal> value);
    partial void OnE_TITLE_TYPEChanged();
    partial void OnE_TITLEChanging(System.Nullable<decimal> value);
    partial void OnE_TITLEChanged();
    partial void OnE_TITLE_DESCChanging(string value);
    partial void OnE_TITLE_DESCChanged();
    partial void OnE_TITLE_FULL_DESCChanging(string value);
    partial void OnE_TITLE_FULL_DESCChanged();
    partial void OnE_TITLE1Changing(string value);
    partial void OnE_TITLE1Changed();
    partial void OnE_TITLE1_DESCChanging(string value);
    partial void OnE_TITLE1_DESCChanged();
    partial void OnE_TITLE2Changing(string value);
    partial void OnE_TITLE2Changed();
    partial void OnE_TITLE2_DESCChanging(string value);
    partial void OnE_TITLE2_DESCChanged();
    partial void OnE_TITLE3Changing(string value);
    partial void OnE_TITLE3Changed();
    partial void OnE_TITLE3_DESCChanging(string value);
    partial void OnE_TITLE3_DESCChanged();
    partial void OnE_TITLE4Changing(string value);
    partial void OnE_TITLE4Changed();
    partial void OnE_TITLE4_DESCChanging(string value);
    partial void OnE_TITLE4_DESCChanged();
    partial void OnE_NAMEFChanging(string value);
    partial void OnE_NAMEFChanged();
    partial void OnE_NAMELChanging(string value);
    partial void OnE_NAMELChanged();
    partial void OnE_PERM_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_PERM_DATEChanged();
    partial void OnE_BIRTH_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_BIRTH_DATEChanged();
    partial void OnE_ENTRY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_ENTRY_DATEChanged();
    partial void OnE_POSI_STChanging(string value);
    partial void OnE_POSI_STChanged();
    partial void OnE_POS_ST_DESCChanging(string value);
    partial void OnE_POS_ST_DESCChanged();
    partial void OnE_POSI_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_POSI_DATEChanged();
    partial void OnE_STAFF_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_STAFF_DATEChanged();
    partial void OnE_RELIGIONChanging(string value);
    partial void OnE_RELIGIONChanged();
    partial void OnE_RELG_NAMEChanging(string value);
    partial void OnE_RELG_NAMEChanged();
    partial void OnE_RACEChanging(string value);
    partial void OnE_RACEChanged();
    partial void OnRACE_NAMEChanging(string value);
    partial void OnRACE_NAMEChanged();
    partial void OnE_NATIONALITYChanging(string value);
    partial void OnE_NATIONALITYChanged();
    partial void OnNATIONALITY_NAMEChanging(string value);
    partial void OnNATIONALITY_NAMEChanged();
    partial void OnE_MARITAL_STChanging(string value);
    partial void OnE_MARITAL_STChanged();
    partial void OnE_MARITAL_ST_DESCChanging(string value);
    partial void OnE_MARITAL_ST_DESCChanged();
    partial void OnE_SEXChanging(string value);
    partial void OnE_SEXChanged();
    partial void OnE_SEX_DESCChanging(string value);
    partial void OnE_SEX_DESCChanged();
    partial void OnE_POSI_CODEChanging(string value);
    partial void OnE_POSI_CODEChanged();
    partial void OnE_POST_TEXT_SHORTChanging(string value);
    partial void OnE_POST_TEXT_SHORTChanged();
    partial void OnE_POST_TEXTChanging(string value);
    partial void OnE_POST_TEXTChanged();
    partial void OnE_LEVEL_CODEChanging(string value);
    partial void OnE_LEVEL_CODEChanged();
    partial void OnE_LEVEL_DESCChanging(string value);
    partial void OnE_LEVEL_DESCChanged();
    partial void OnDEPT_STABLE_CODEChanging(string value);
    partial void OnDEPT_STABLE_CODEChanged();
    partial void OnDEPT_CHANGE_CODEChanging(string value);
    partial void OnDEPT_CHANGE_CODEChanged();
    partial void OnDEPT_SHORTChanging(string value);
    partial void OnDEPT_SHORTChanged();
    partial void OnDEPT_FULLChanging(string value);
    partial void OnDEPT_FULLChanged();
    partial void OnE_RETIREDChanging(System.Nullable<System.DateTime> value);
    partial void OnE_RETIREDChanged();
    partial void OnE_EMP_STChanging(string value);
    partial void OnE_EMP_STChanged();
    partial void OnE_EMP_ST_DESCChanging(string value);
    partial void OnE_EMP_ST_DESCChanged();
    partial void OnE_UPD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_UPD_DATEChanged();
    partial void OnE_RETIRED2_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_RETIRED2_DATEChanged();
    partial void OnE_QUALIFChanging(System.Nullable<decimal> value);
    partial void OnE_QUALIFChanged();
    partial void OnE_QUALIF_DESCChanging(string value);
    partial void OnE_QUALIF_DESCChanged();
    partial void OnE_QUALIF_LEVELChanging(string value);
    partial void OnE_QUALIF_LEVELChanged();
    partial void OnE_QUALIF_LEVEL_DESCChanging(string value);
    partial void OnE_QUALIF_LEVEL_DESCChanged();
    partial void OnE_DEPTChanging(System.Nullable<decimal> value);
    partial void OnE_DEPTChanged();
    partial void OnE_DEPT_DESCChanging(string value);
    partial void OnE_DEPT_DESCChanged();
    partial void OnE_BLOOD_GROUPChanging(string value);
    partial void OnE_BLOOD_GROUPChanged();
    partial void OnE_IDENTITY_NOChanging(string value);
    partial void OnE_IDENTITY_NOChanged();
    partial void OnE_DEPT_SAPChanging(string value);
    partial void OnE_DEPT_SAPChanged();
    partial void OnE_DEPT_SHORTChanging(string value);
    partial void OnE_DEPT_SHORTChanged();
    partial void OnE_DEPT_FULLChanging(string value);
    partial void OnE_DEPT_FULLChanged();
    partial void OnE_REGChanging(string value);
    partial void OnE_REGChanged();
    partial void OnE_REG_NAMEChanging(string value);
    partial void OnE_REG_NAMEChanged();
    partial void OnE_SUB_REGChanging(string value);
    partial void OnE_SUB_REGChanged();
    partial void OnE_SUB_REG_NAMEChanging(string value);
    partial void OnE_SUB_REG_NAMEChanged();
    partial void OnE_COST_CENTERChanging(string value);
    partial void OnE_COST_CENTERChanged();
    partial void OnE_COST_CENTER_NAMEChanging(string value);
    partial void OnE_COST_CENTER_NAMEChanged();
    partial void OnE_BAChanging(string value);
    partial void OnE_BAChanged();
    partial void OnE_BA_NAMEChanging(string value);
    partial void OnE_BA_NAMEChanged();
    partial void OnE_PY_AREAChanging(string value);
    partial void OnE_PY_AREAChanged();
    partial void OnE_PY_AREA_NAMEChanging(string value);
    partial void OnE_PY_AREA_NAMEChanged();
    partial void OnE_VENDOR_CODEChanging(string value);
    partial void OnE_VENDOR_CODEChanged();
    partial void OnE_BEG_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_BEG_DATEChanged();
    partial void OnE_CONT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_CONT_DATEChanged();
    partial void OnE_END_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_END_DATEChanged();
    #endregion
		
		public EMPLOYEE_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ID", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string E_ID
		{
			get
			{
				return this._E_ID;
			}
			set
			{
				if ((this._E_ID != value))
				{
					this.OnE_IDChanging(value);
					this.SendPropertyChanging();
					this._E_ID = value;
					this.SendPropertyChanged("E_ID");
					this.OnE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE_TYPE", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> E_TITLE_TYPE
		{
			get
			{
				return this._E_TITLE_TYPE;
			}
			set
			{
				if ((this._E_TITLE_TYPE != value))
				{
					this.OnE_TITLE_TYPEChanging(value);
					this.SendPropertyChanging();
					this._E_TITLE_TYPE = value;
					this.SendPropertyChanged("E_TITLE_TYPE");
					this.OnE_TITLE_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> E_TITLE
		{
			get
			{
				return this._E_TITLE;
			}
			set
			{
				if ((this._E_TITLE != value))
				{
					this.OnE_TITLEChanging(value);
					this.SendPropertyChanging();
					this._E_TITLE = value;
					this.SendPropertyChanged("E_TITLE");
					this.OnE_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE_DESC", DbType="VarChar(5)")]
		public string E_TITLE_DESC
		{
			get
			{
				return this._E_TITLE_DESC;
			}
			set
			{
				if ((this._E_TITLE_DESC != value))
				{
					this.OnE_TITLE_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_TITLE_DESC = value;
					this.SendPropertyChanged("E_TITLE_DESC");
					this.OnE_TITLE_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE_FULL_DESC", DbType="VarChar(15)")]
		public string E_TITLE_FULL_DESC
		{
			get
			{
				return this._E_TITLE_FULL_DESC;
			}
			set
			{
				if ((this._E_TITLE_FULL_DESC != value))
				{
					this.OnE_TITLE_FULL_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_TITLE_FULL_DESC = value;
					this.SendPropertyChanged("E_TITLE_FULL_DESC");
					this.OnE_TITLE_FULL_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE1", DbType="VarChar(15)")]
		public string E_TITLE1
		{
			get
			{
				return this._E_TITLE1;
			}
			set
			{
				if ((this._E_TITLE1 != value))
				{
					this.OnE_TITLE1Changing(value);
					this.SendPropertyChanging();
					this._E_TITLE1 = value;
					this.SendPropertyChanged("E_TITLE1");
					this.OnE_TITLE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE1_DESC", DbType="VarChar(15)")]
		public string E_TITLE1_DESC
		{
			get
			{
				return this._E_TITLE1_DESC;
			}
			set
			{
				if ((this._E_TITLE1_DESC != value))
				{
					this.OnE_TITLE1_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_TITLE1_DESC = value;
					this.SendPropertyChanged("E_TITLE1_DESC");
					this.OnE_TITLE1_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE2", DbType="VarChar(15)")]
		public string E_TITLE2
		{
			get
			{
				return this._E_TITLE2;
			}
			set
			{
				if ((this._E_TITLE2 != value))
				{
					this.OnE_TITLE2Changing(value);
					this.SendPropertyChanging();
					this._E_TITLE2 = value;
					this.SendPropertyChanged("E_TITLE2");
					this.OnE_TITLE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE2_DESC", DbType="VarChar(15)")]
		public string E_TITLE2_DESC
		{
			get
			{
				return this._E_TITLE2_DESC;
			}
			set
			{
				if ((this._E_TITLE2_DESC != value))
				{
					this.OnE_TITLE2_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_TITLE2_DESC = value;
					this.SendPropertyChanged("E_TITLE2_DESC");
					this.OnE_TITLE2_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE3", DbType="VarChar(15)")]
		public string E_TITLE3
		{
			get
			{
				return this._E_TITLE3;
			}
			set
			{
				if ((this._E_TITLE3 != value))
				{
					this.OnE_TITLE3Changing(value);
					this.SendPropertyChanging();
					this._E_TITLE3 = value;
					this.SendPropertyChanged("E_TITLE3");
					this.OnE_TITLE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE3_DESC", DbType="VarChar(15)")]
		public string E_TITLE3_DESC
		{
			get
			{
				return this._E_TITLE3_DESC;
			}
			set
			{
				if ((this._E_TITLE3_DESC != value))
				{
					this.OnE_TITLE3_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_TITLE3_DESC = value;
					this.SendPropertyChanged("E_TITLE3_DESC");
					this.OnE_TITLE3_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE4", DbType="VarChar(15)")]
		public string E_TITLE4
		{
			get
			{
				return this._E_TITLE4;
			}
			set
			{
				if ((this._E_TITLE4 != value))
				{
					this.OnE_TITLE4Changing(value);
					this.SendPropertyChanging();
					this._E_TITLE4 = value;
					this.SendPropertyChanged("E_TITLE4");
					this.OnE_TITLE4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_TITLE4_DESC", DbType="VarChar(15)")]
		public string E_TITLE4_DESC
		{
			get
			{
				return this._E_TITLE4_DESC;
			}
			set
			{
				if ((this._E_TITLE4_DESC != value))
				{
					this.OnE_TITLE4_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_TITLE4_DESC = value;
					this.SendPropertyChanged("E_TITLE4_DESC");
					this.OnE_TITLE4_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_NAMEF", DbType="VarChar(40)")]
		public string E_NAMEF
		{
			get
			{
				return this._E_NAMEF;
			}
			set
			{
				if ((this._E_NAMEF != value))
				{
					this.OnE_NAMEFChanging(value);
					this.SendPropertyChanging();
					this._E_NAMEF = value;
					this.SendPropertyChanged("E_NAMEF");
					this.OnE_NAMEFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_NAMEL", DbType="VarChar(40)")]
		public string E_NAMEL
		{
			get
			{
				return this._E_NAMEL;
			}
			set
			{
				if ((this._E_NAMEL != value))
				{
					this.OnE_NAMELChanging(value);
					this.SendPropertyChanging();
					this._E_NAMEL = value;
					this.SendPropertyChanged("E_NAMEL");
					this.OnE_NAMELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_PERM_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_PERM_DATE
		{
			get
			{
				return this._E_PERM_DATE;
			}
			set
			{
				if ((this._E_PERM_DATE != value))
				{
					this.OnE_PERM_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_PERM_DATE = value;
					this.SendPropertyChanged("E_PERM_DATE");
					this.OnE_PERM_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_BIRTH_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_BIRTH_DATE
		{
			get
			{
				return this._E_BIRTH_DATE;
			}
			set
			{
				if ((this._E_BIRTH_DATE != value))
				{
					this.OnE_BIRTH_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_BIRTH_DATE = value;
					this.SendPropertyChanged("E_BIRTH_DATE");
					this.OnE_BIRTH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ENTRY_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_ENTRY_DATE
		{
			get
			{
				return this._E_ENTRY_DATE;
			}
			set
			{
				if ((this._E_ENTRY_DATE != value))
				{
					this.OnE_ENTRY_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_ENTRY_DATE = value;
					this.SendPropertyChanged("E_ENTRY_DATE");
					this.OnE_ENTRY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_POSI_ST", DbType="VarChar(1)")]
		public string E_POSI_ST
		{
			get
			{
				return this._E_POSI_ST;
			}
			set
			{
				if ((this._E_POSI_ST != value))
				{
					this.OnE_POSI_STChanging(value);
					this.SendPropertyChanging();
					this._E_POSI_ST = value;
					this.SendPropertyChanged("E_POSI_ST");
					this.OnE_POSI_STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_POS_ST_DESC", DbType="VarChar(20)")]
		public string E_POS_ST_DESC
		{
			get
			{
				return this._E_POS_ST_DESC;
			}
			set
			{
				if ((this._E_POS_ST_DESC != value))
				{
					this.OnE_POS_ST_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_POS_ST_DESC = value;
					this.SendPropertyChanged("E_POS_ST_DESC");
					this.OnE_POS_ST_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_POSI_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_POSI_DATE
		{
			get
			{
				return this._E_POSI_DATE;
			}
			set
			{
				if ((this._E_POSI_DATE != value))
				{
					this.OnE_POSI_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_POSI_DATE = value;
					this.SendPropertyChanged("E_POSI_DATE");
					this.OnE_POSI_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_STAFF_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_STAFF_DATE
		{
			get
			{
				return this._E_STAFF_DATE;
			}
			set
			{
				if ((this._E_STAFF_DATE != value))
				{
					this.OnE_STAFF_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_STAFF_DATE = value;
					this.SendPropertyChanged("E_STAFF_DATE");
					this.OnE_STAFF_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_RELIGION", DbType="VarChar(2)")]
		public string E_RELIGION
		{
			get
			{
				return this._E_RELIGION;
			}
			set
			{
				if ((this._E_RELIGION != value))
				{
					this.OnE_RELIGIONChanging(value);
					this.SendPropertyChanging();
					this._E_RELIGION = value;
					this.SendPropertyChanged("E_RELIGION");
					this.OnE_RELIGIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_RELG_NAME", DbType="VarChar(25)")]
		public string E_RELG_NAME
		{
			get
			{
				return this._E_RELG_NAME;
			}
			set
			{
				if ((this._E_RELG_NAME != value))
				{
					this.OnE_RELG_NAMEChanging(value);
					this.SendPropertyChanging();
					this._E_RELG_NAME = value;
					this.SendPropertyChanged("E_RELG_NAME");
					this.OnE_RELG_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_RACE", DbType="VarChar(2)")]
		public string E_RACE
		{
			get
			{
				return this._E_RACE;
			}
			set
			{
				if ((this._E_RACE != value))
				{
					this.OnE_RACEChanging(value);
					this.SendPropertyChanging();
					this._E_RACE = value;
					this.SendPropertyChanged("E_RACE");
					this.OnE_RACEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_NAME", DbType="VarChar(50)")]
		public string RACE_NAME
		{
			get
			{
				return this._RACE_NAME;
			}
			set
			{
				if ((this._RACE_NAME != value))
				{
					this.OnRACE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._RACE_NAME = value;
					this.SendPropertyChanged("RACE_NAME");
					this.OnRACE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_NATIONALITY", DbType="VarChar(3)")]
		public string E_NATIONALITY
		{
			get
			{
				return this._E_NATIONALITY;
			}
			set
			{
				if ((this._E_NATIONALITY != value))
				{
					this.OnE_NATIONALITYChanging(value);
					this.SendPropertyChanging();
					this._E_NATIONALITY = value;
					this.SendPropertyChanged("E_NATIONALITY");
					this.OnE_NATIONALITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATIONALITY_NAME", DbType="VarChar(50)")]
		public string NATIONALITY_NAME
		{
			get
			{
				return this._NATIONALITY_NAME;
			}
			set
			{
				if ((this._NATIONALITY_NAME != value))
				{
					this.OnNATIONALITY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._NATIONALITY_NAME = value;
					this.SendPropertyChanged("NATIONALITY_NAME");
					this.OnNATIONALITY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_MARITAL_ST", DbType="VarChar(1)")]
		public string E_MARITAL_ST
		{
			get
			{
				return this._E_MARITAL_ST;
			}
			set
			{
				if ((this._E_MARITAL_ST != value))
				{
					this.OnE_MARITAL_STChanging(value);
					this.SendPropertyChanging();
					this._E_MARITAL_ST = value;
					this.SendPropertyChanged("E_MARITAL_ST");
					this.OnE_MARITAL_STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_MARITAL_ST_DESC", DbType="VarChar(6)")]
		public string E_MARITAL_ST_DESC
		{
			get
			{
				return this._E_MARITAL_ST_DESC;
			}
			set
			{
				if ((this._E_MARITAL_ST_DESC != value))
				{
					this.OnE_MARITAL_ST_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_MARITAL_ST_DESC = value;
					this.SendPropertyChanged("E_MARITAL_ST_DESC");
					this.OnE_MARITAL_ST_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_SEX", DbType="VarChar(1)")]
		public string E_SEX
		{
			get
			{
				return this._E_SEX;
			}
			set
			{
				if ((this._E_SEX != value))
				{
					this.OnE_SEXChanging(value);
					this.SendPropertyChanging();
					this._E_SEX = value;
					this.SendPropertyChanged("E_SEX");
					this.OnE_SEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_SEX_DESC", DbType="VarChar(4)")]
		public string E_SEX_DESC
		{
			get
			{
				return this._E_SEX_DESC;
			}
			set
			{
				if ((this._E_SEX_DESC != value))
				{
					this.OnE_SEX_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_SEX_DESC = value;
					this.SendPropertyChanged("E_SEX_DESC");
					this.OnE_SEX_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_POSI_CODE", DbType="VarChar(4)")]
		public string E_POSI_CODE
		{
			get
			{
				return this._E_POSI_CODE;
			}
			set
			{
				if ((this._E_POSI_CODE != value))
				{
					this.OnE_POSI_CODEChanging(value);
					this.SendPropertyChanging();
					this._E_POSI_CODE = value;
					this.SendPropertyChanged("E_POSI_CODE");
					this.OnE_POSI_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_POST_TEXT_SHORT", DbType="VarChar(12)")]
		public string E_POST_TEXT_SHORT
		{
			get
			{
				return this._E_POST_TEXT_SHORT;
			}
			set
			{
				if ((this._E_POST_TEXT_SHORT != value))
				{
					this.OnE_POST_TEXT_SHORTChanging(value);
					this.SendPropertyChanging();
					this._E_POST_TEXT_SHORT = value;
					this.SendPropertyChanged("E_POST_TEXT_SHORT");
					this.OnE_POST_TEXT_SHORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_POST_TEXT", DbType="VarChar(40)")]
		public string E_POST_TEXT
		{
			get
			{
				return this._E_POST_TEXT;
			}
			set
			{
				if ((this._E_POST_TEXT != value))
				{
					this.OnE_POST_TEXTChanging(value);
					this.SendPropertyChanging();
					this._E_POST_TEXT = value;
					this.SendPropertyChanged("E_POST_TEXT");
					this.OnE_POST_TEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_LEVEL_CODE", DbType="VarChar(2)")]
		public string E_LEVEL_CODE
		{
			get
			{
				return this._E_LEVEL_CODE;
			}
			set
			{
				if ((this._E_LEVEL_CODE != value))
				{
					this.OnE_LEVEL_CODEChanging(value);
					this.SendPropertyChanging();
					this._E_LEVEL_CODE = value;
					this.SendPropertyChanged("E_LEVEL_CODE");
					this.OnE_LEVEL_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_LEVEL_DESC", DbType="VarChar(20)")]
		public string E_LEVEL_DESC
		{
			get
			{
				return this._E_LEVEL_DESC;
			}
			set
			{
				if ((this._E_LEVEL_DESC != value))
				{
					this.OnE_LEVEL_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_LEVEL_DESC = value;
					this.SendPropertyChanged("E_LEVEL_DESC");
					this.OnE_LEVEL_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_STABLE_CODE", DbType="VarChar(6)")]
		public string DEPT_STABLE_CODE
		{
			get
			{
				return this._DEPT_STABLE_CODE;
			}
			set
			{
				if ((this._DEPT_STABLE_CODE != value))
				{
					this.OnDEPT_STABLE_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEPT_STABLE_CODE = value;
					this.SendPropertyChanged("DEPT_STABLE_CODE");
					this.OnDEPT_STABLE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CHANGE_CODE", DbType="VarChar(15)")]
		public string DEPT_CHANGE_CODE
		{
			get
			{
				return this._DEPT_CHANGE_CODE;
			}
			set
			{
				if ((this._DEPT_CHANGE_CODE != value))
				{
					this.OnDEPT_CHANGE_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEPT_CHANGE_CODE = value;
					this.SendPropertyChanged("DEPT_CHANGE_CODE");
					this.OnDEPT_CHANGE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_SHORT", DbType="VarChar(12)")]
		public string DEPT_SHORT
		{
			get
			{
				return this._DEPT_SHORT;
			}
			set
			{
				if ((this._DEPT_SHORT != value))
				{
					this.OnDEPT_SHORTChanging(value);
					this.SendPropertyChanging();
					this._DEPT_SHORT = value;
					this.SendPropertyChanged("DEPT_SHORT");
					this.OnDEPT_SHORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_FULL", DbType="VarChar(40)")]
		public string DEPT_FULL
		{
			get
			{
				return this._DEPT_FULL;
			}
			set
			{
				if ((this._DEPT_FULL != value))
				{
					this.OnDEPT_FULLChanging(value);
					this.SendPropertyChanging();
					this._DEPT_FULL = value;
					this.SendPropertyChanged("DEPT_FULL");
					this.OnDEPT_FULLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_RETIRED", DbType="Date")]
		public System.Nullable<System.DateTime> E_RETIRED
		{
			get
			{
				return this._E_RETIRED;
			}
			set
			{
				if ((this._E_RETIRED != value))
				{
					this.OnE_RETIREDChanging(value);
					this.SendPropertyChanging();
					this._E_RETIRED = value;
					this.SendPropertyChanged("E_RETIRED");
					this.OnE_RETIREDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_EMP_ST", DbType="VarChar(1)")]
		public string E_EMP_ST
		{
			get
			{
				return this._E_EMP_ST;
			}
			set
			{
				if ((this._E_EMP_ST != value))
				{
					this.OnE_EMP_STChanging(value);
					this.SendPropertyChanging();
					this._E_EMP_ST = value;
					this.SendPropertyChanged("E_EMP_ST");
					this.OnE_EMP_STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_EMP_ST_DESC", DbType="VarChar(30)")]
		public string E_EMP_ST_DESC
		{
			get
			{
				return this._E_EMP_ST_DESC;
			}
			set
			{
				if ((this._E_EMP_ST_DESC != value))
				{
					this.OnE_EMP_ST_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_EMP_ST_DESC = value;
					this.SendPropertyChanged("E_EMP_ST_DESC");
					this.OnE_EMP_ST_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_UPD_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_UPD_DATE
		{
			get
			{
				return this._E_UPD_DATE;
			}
			set
			{
				if ((this._E_UPD_DATE != value))
				{
					this.OnE_UPD_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_UPD_DATE = value;
					this.SendPropertyChanged("E_UPD_DATE");
					this.OnE_UPD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_RETIRED2_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_RETIRED2_DATE
		{
			get
			{
				return this._E_RETIRED2_DATE;
			}
			set
			{
				if ((this._E_RETIRED2_DATE != value))
				{
					this.OnE_RETIRED2_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_RETIRED2_DATE = value;
					this.SendPropertyChanged("E_RETIRED2_DATE");
					this.OnE_RETIRED2_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_QUALIF", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> E_QUALIF
		{
			get
			{
				return this._E_QUALIF;
			}
			set
			{
				if ((this._E_QUALIF != value))
				{
					this.OnE_QUALIFChanging(value);
					this.SendPropertyChanging();
					this._E_QUALIF = value;
					this.SendPropertyChanged("E_QUALIF");
					this.OnE_QUALIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_QUALIF_DESC", DbType="VarChar(40)")]
		public string E_QUALIF_DESC
		{
			get
			{
				return this._E_QUALIF_DESC;
			}
			set
			{
				if ((this._E_QUALIF_DESC != value))
				{
					this.OnE_QUALIF_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_QUALIF_DESC = value;
					this.SendPropertyChanged("E_QUALIF_DESC");
					this.OnE_QUALIF_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_QUALIF_LEVEL", DbType="VarChar(2)")]
		public string E_QUALIF_LEVEL
		{
			get
			{
				return this._E_QUALIF_LEVEL;
			}
			set
			{
				if ((this._E_QUALIF_LEVEL != value))
				{
					this.OnE_QUALIF_LEVELChanging(value);
					this.SendPropertyChanging();
					this._E_QUALIF_LEVEL = value;
					this.SendPropertyChanged("E_QUALIF_LEVEL");
					this.OnE_QUALIF_LEVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_QUALIF_LEVEL_DESC", DbType="VarChar(20)")]
		public string E_QUALIF_LEVEL_DESC
		{
			get
			{
				return this._E_QUALIF_LEVEL_DESC;
			}
			set
			{
				if ((this._E_QUALIF_LEVEL_DESC != value))
				{
					this.OnE_QUALIF_LEVEL_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_QUALIF_LEVEL_DESC = value;
					this.SendPropertyChanged("E_QUALIF_LEVEL_DESC");
					this.OnE_QUALIF_LEVEL_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DEPT", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> E_DEPT
		{
			get
			{
				return this._E_DEPT;
			}
			set
			{
				if ((this._E_DEPT != value))
				{
					this.OnE_DEPTChanging(value);
					this.SendPropertyChanging();
					this._E_DEPT = value;
					this.SendPropertyChanged("E_DEPT");
					this.OnE_DEPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DEPT_DESC", DbType="VarChar(40)")]
		public string E_DEPT_DESC
		{
			get
			{
				return this._E_DEPT_DESC;
			}
			set
			{
				if ((this._E_DEPT_DESC != value))
				{
					this.OnE_DEPT_DESCChanging(value);
					this.SendPropertyChanging();
					this._E_DEPT_DESC = value;
					this.SendPropertyChanged("E_DEPT_DESC");
					this.OnE_DEPT_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_BLOOD_GROUP", DbType="VarChar(2)")]
		public string E_BLOOD_GROUP
		{
			get
			{
				return this._E_BLOOD_GROUP;
			}
			set
			{
				if ((this._E_BLOOD_GROUP != value))
				{
					this.OnE_BLOOD_GROUPChanging(value);
					this.SendPropertyChanging();
					this._E_BLOOD_GROUP = value;
					this.SendPropertyChanged("E_BLOOD_GROUP");
					this.OnE_BLOOD_GROUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_IDENTITY_NO", DbType="VarChar(30)")]
		public string E_IDENTITY_NO
		{
			get
			{
				return this._E_IDENTITY_NO;
			}
			set
			{
				if ((this._E_IDENTITY_NO != value))
				{
					this.OnE_IDENTITY_NOChanging(value);
					this.SendPropertyChanging();
					this._E_IDENTITY_NO = value;
					this.SendPropertyChanged("E_IDENTITY_NO");
					this.OnE_IDENTITY_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DEPT_SAP", DbType="VarChar(8)")]
		public string E_DEPT_SAP
		{
			get
			{
				return this._E_DEPT_SAP;
			}
			set
			{
				if ((this._E_DEPT_SAP != value))
				{
					this.OnE_DEPT_SAPChanging(value);
					this.SendPropertyChanging();
					this._E_DEPT_SAP = value;
					this.SendPropertyChanged("E_DEPT_SAP");
					this.OnE_DEPT_SAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DEPT_SHORT", DbType="VarChar(250)")]
		public string E_DEPT_SHORT
		{
			get
			{
				return this._E_DEPT_SHORT;
			}
			set
			{
				if ((this._E_DEPT_SHORT != value))
				{
					this.OnE_DEPT_SHORTChanging(value);
					this.SendPropertyChanging();
					this._E_DEPT_SHORT = value;
					this.SendPropertyChanged("E_DEPT_SHORT");
					this.OnE_DEPT_SHORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DEPT_FULL", DbType="VarChar(250)")]
		public string E_DEPT_FULL
		{
			get
			{
				return this._E_DEPT_FULL;
			}
			set
			{
				if ((this._E_DEPT_FULL != value))
				{
					this.OnE_DEPT_FULLChanging(value);
					this.SendPropertyChanging();
					this._E_DEPT_FULL = value;
					this.SendPropertyChanged("E_DEPT_FULL");
					this.OnE_DEPT_FULLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_REG", DbType="VarChar(4)")]
		public string E_REG
		{
			get
			{
				return this._E_REG;
			}
			set
			{
				if ((this._E_REG != value))
				{
					this.OnE_REGChanging(value);
					this.SendPropertyChanging();
					this._E_REG = value;
					this.SendPropertyChanged("E_REG");
					this.OnE_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_REG_NAME", DbType="VarChar(50)")]
		public string E_REG_NAME
		{
			get
			{
				return this._E_REG_NAME;
			}
			set
			{
				if ((this._E_REG_NAME != value))
				{
					this.OnE_REG_NAMEChanging(value);
					this.SendPropertyChanging();
					this._E_REG_NAME = value;
					this.SendPropertyChanged("E_REG_NAME");
					this.OnE_REG_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_SUB_REG", DbType="VarChar(4)")]
		public string E_SUB_REG
		{
			get
			{
				return this._E_SUB_REG;
			}
			set
			{
				if ((this._E_SUB_REG != value))
				{
					this.OnE_SUB_REGChanging(value);
					this.SendPropertyChanging();
					this._E_SUB_REG = value;
					this.SendPropertyChanged("E_SUB_REG");
					this.OnE_SUB_REGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_SUB_REG_NAME", DbType="VarChar(20)")]
		public string E_SUB_REG_NAME
		{
			get
			{
				return this._E_SUB_REG_NAME;
			}
			set
			{
				if ((this._E_SUB_REG_NAME != value))
				{
					this.OnE_SUB_REG_NAMEChanging(value);
					this.SendPropertyChanging();
					this._E_SUB_REG_NAME = value;
					this.SendPropertyChanged("E_SUB_REG_NAME");
					this.OnE_SUB_REG_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_COST_CENTER", DbType="VarChar(10)")]
		public string E_COST_CENTER
		{
			get
			{
				return this._E_COST_CENTER;
			}
			set
			{
				if ((this._E_COST_CENTER != value))
				{
					this.OnE_COST_CENTERChanging(value);
					this.SendPropertyChanging();
					this._E_COST_CENTER = value;
					this.SendPropertyChanged("E_COST_CENTER");
					this.OnE_COST_CENTERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_COST_CENTER_NAME", DbType="VarChar(100)")]
		public string E_COST_CENTER_NAME
		{
			get
			{
				return this._E_COST_CENTER_NAME;
			}
			set
			{
				if ((this._E_COST_CENTER_NAME != value))
				{
					this.OnE_COST_CENTER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._E_COST_CENTER_NAME = value;
					this.SendPropertyChanged("E_COST_CENTER_NAME");
					this.OnE_COST_CENTER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_BA", DbType="VarChar(4)")]
		public string E_BA
		{
			get
			{
				return this._E_BA;
			}
			set
			{
				if ((this._E_BA != value))
				{
					this.OnE_BAChanging(value);
					this.SendPropertyChanging();
					this._E_BA = value;
					this.SendPropertyChanged("E_BA");
					this.OnE_BAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_BA_NAME", DbType="VarChar(60)")]
		public string E_BA_NAME
		{
			get
			{
				return this._E_BA_NAME;
			}
			set
			{
				if ((this._E_BA_NAME != value))
				{
					this.OnE_BA_NAMEChanging(value);
					this.SendPropertyChanging();
					this._E_BA_NAME = value;
					this.SendPropertyChanged("E_BA_NAME");
					this.OnE_BA_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_PY_AREA", DbType="VarChar(2)")]
		public string E_PY_AREA
		{
			get
			{
				return this._E_PY_AREA;
			}
			set
			{
				if ((this._E_PY_AREA != value))
				{
					this.OnE_PY_AREAChanging(value);
					this.SendPropertyChanging();
					this._E_PY_AREA = value;
					this.SendPropertyChanged("E_PY_AREA");
					this.OnE_PY_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_PY_AREA_NAME", DbType="VarChar(50)")]
		public string E_PY_AREA_NAME
		{
			get
			{
				return this._E_PY_AREA_NAME;
			}
			set
			{
				if ((this._E_PY_AREA_NAME != value))
				{
					this.OnE_PY_AREA_NAMEChanging(value);
					this.SendPropertyChanging();
					this._E_PY_AREA_NAME = value;
					this.SendPropertyChanged("E_PY_AREA_NAME");
					this.OnE_PY_AREA_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_VENDOR_CODE", DbType="VarChar(10)")]
		public string E_VENDOR_CODE
		{
			get
			{
				return this._E_VENDOR_CODE;
			}
			set
			{
				if ((this._E_VENDOR_CODE != value))
				{
					this.OnE_VENDOR_CODEChanging(value);
					this.SendPropertyChanging();
					this._E_VENDOR_CODE = value;
					this.SendPropertyChanged("E_VENDOR_CODE");
					this.OnE_VENDOR_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_BEG_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_BEG_DATE
		{
			get
			{
				return this._E_BEG_DATE;
			}
			set
			{
				if ((this._E_BEG_DATE != value))
				{
					this.OnE_BEG_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_BEG_DATE = value;
					this.SendPropertyChanged("E_BEG_DATE");
					this.OnE_BEG_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_CONT_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_CONT_DATE
		{
			get
			{
				return this._E_CONT_DATE;
			}
			set
			{
				if ((this._E_CONT_DATE != value))
				{
					this.OnE_CONT_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_CONT_DATE = value;
					this.SendPropertyChanged("E_CONT_DATE");
					this.OnE_CONT_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_END_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_END_DATE
		{
			get
			{
				return this._E_END_DATE;
			}
			set
			{
				if ((this._E_END_DATE != value))
				{
					this.OnE_END_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_END_DATE = value;
					this.SendPropertyChanged("E_END_DATE");
					this.OnE_END_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAX_Desc")]
	public partial class TAX_Desc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Description;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public TAX_Desc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PA0364")]
	public partial class PA0364 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PERNR;
		
		private System.Nullable<System.DateTime> _ENDDA;
		
		private System.DateTime _BEGDA;
		
		private System.Nullable<System.DateTime> _AEDTM;
		
		private string _UNAME;
		
		private string _TAXID;
		
		private System.Nullable<char> _SPALL;
		
		private System.Nullable<decimal> _LPREM;
		
		private System.Nullable<decimal> _MGINT;
		
		private System.Nullable<decimal> _CHAMT;
		
		private string _CHNO1;
		
		private string _CHNO2;
		
		private string _CHNO3;
		
		private System.Nullable<decimal> _SPINS;
		
		private string _ALLTY;
		
		private System.Nullable<decimal> _MFINV;
		
		private System.Nullable<decimal> _HACSH;
		
		private System.Nullable<decimal> _HAHIR;
		
		private System.Nullable<decimal> _PENSN;
		
		private System.Nullable<decimal> _LTEQF;
		
		private System.Nullable<decimal> _CHEDU;
		
		private System.Nullable<decimal> _FCNTR;
		
		private System.Nullable<decimal> _MCNTR;
		
		private System.Nullable<decimal> _SFCTR;
		
		private System.Nullable<decimal> _SMCTR;
		
		private System.Nullable<decimal> _SPRCTR;
		
		private System.Nullable<decimal> _FPRINS;
		
		private System.Nullable<decimal> _MPRINS;
		
		private System.Nullable<decimal> _SFPINS;
		
		private System.Nullable<decimal> _SMPINS;
		
		private System.Nullable<decimal> _IMMEXP;
		
		private System.Nullable<char> _DIALL;
		
		private System.Nullable<char> _DINO1;
		
		private System.Nullable<char> _CHECK_STATUS;
		
		private System.Nullable<System.DateTime> _CHECK_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPERNRChanging(string value);
    partial void OnPERNRChanged();
    partial void OnENDDAChanging(System.Nullable<System.DateTime> value);
    partial void OnENDDAChanged();
    partial void OnBEGDAChanging(System.DateTime value);
    partial void OnBEGDAChanged();
    partial void OnAEDTMChanging(System.Nullable<System.DateTime> value);
    partial void OnAEDTMChanged();
    partial void OnUNAMEChanging(string value);
    partial void OnUNAMEChanged();
    partial void OnTAXIDChanging(string value);
    partial void OnTAXIDChanged();
    partial void OnSPALLChanging(System.Nullable<char> value);
    partial void OnSPALLChanged();
    partial void OnLPREMChanging(System.Nullable<decimal> value);
    partial void OnLPREMChanged();
    partial void OnMGINTChanging(System.Nullable<decimal> value);
    partial void OnMGINTChanged();
    partial void OnCHAMTChanging(System.Nullable<decimal> value);
    partial void OnCHAMTChanged();
    partial void OnCHNO1Changing(string value);
    partial void OnCHNO1Changed();
    partial void OnCHNO2Changing(string value);
    partial void OnCHNO2Changed();
    partial void OnCHNO3Changing(string value);
    partial void OnCHNO3Changed();
    partial void OnSPINSChanging(System.Nullable<decimal> value);
    partial void OnSPINSChanged();
    partial void OnALLTYChanging(string value);
    partial void OnALLTYChanged();
    partial void OnMFINVChanging(System.Nullable<decimal> value);
    partial void OnMFINVChanged();
    partial void OnHACSHChanging(System.Nullable<decimal> value);
    partial void OnHACSHChanged();
    partial void OnHAHIRChanging(System.Nullable<decimal> value);
    partial void OnHAHIRChanged();
    partial void OnPENSNChanging(System.Nullable<decimal> value);
    partial void OnPENSNChanged();
    partial void OnLTEQFChanging(System.Nullable<decimal> value);
    partial void OnLTEQFChanged();
    partial void OnCHEDUChanging(System.Nullable<decimal> value);
    partial void OnCHEDUChanged();
    partial void OnFCNTRChanging(System.Nullable<decimal> value);
    partial void OnFCNTRChanged();
    partial void OnMCNTRChanging(System.Nullable<decimal> value);
    partial void OnMCNTRChanged();
    partial void OnSFCTRChanging(System.Nullable<decimal> value);
    partial void OnSFCTRChanged();
    partial void OnSMCTRChanging(System.Nullable<decimal> value);
    partial void OnSMCTRChanged();
    partial void OnSPRCTRChanging(System.Nullable<decimal> value);
    partial void OnSPRCTRChanged();
    partial void OnFPRINSChanging(System.Nullable<decimal> value);
    partial void OnFPRINSChanged();
    partial void OnMPRINSChanging(System.Nullable<decimal> value);
    partial void OnMPRINSChanged();
    partial void OnSFPINSChanging(System.Nullable<decimal> value);
    partial void OnSFPINSChanged();
    partial void OnSMPINSChanging(System.Nullable<decimal> value);
    partial void OnSMPINSChanged();
    partial void OnIMMEXPChanging(System.Nullable<decimal> value);
    partial void OnIMMEXPChanged();
    partial void OnDIALLChanging(System.Nullable<char> value);
    partial void OnDIALLChanged();
    partial void OnDINO1Changing(System.Nullable<char> value);
    partial void OnDINO1Changed();
    partial void OnCHECK_STATUSChanging(System.Nullable<char> value);
    partial void OnCHECK_STATUSChanged();
    partial void OnCHECK_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCHECK_DATEChanged();
    #endregion
		
		public PA0364()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERNR", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PERNR
		{
			get
			{
				return this._PERNR;
			}
			set
			{
				if ((this._PERNR != value))
				{
					this.OnPERNRChanging(value);
					this.SendPropertyChanging();
					this._PERNR = value;
					this.SendPropertyChanged("PERNR");
					this.OnPERNRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDA", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDA
		{
			get
			{
				return this._ENDDA;
			}
			set
			{
				if ((this._ENDDA != value))
				{
					this.OnENDDAChanging(value);
					this.SendPropertyChanging();
					this._ENDDA = value;
					this.SendPropertyChanged("ENDDA");
					this.OnENDDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGDA", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime BEGDA
		{
			get
			{
				return this._BEGDA;
			}
			set
			{
				if ((this._BEGDA != value))
				{
					this.OnBEGDAChanging(value);
					this.SendPropertyChanging();
					this._BEGDA = value;
					this.SendPropertyChanged("BEGDA");
					this.OnBEGDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEDTM", DbType="Date")]
		public System.Nullable<System.DateTime> AEDTM
		{
			get
			{
				return this._AEDTM;
			}
			set
			{
				if ((this._AEDTM != value))
				{
					this.OnAEDTMChanging(value);
					this.SendPropertyChanging();
					this._AEDTM = value;
					this.SendPropertyChanged("AEDTM");
					this.OnAEDTMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNAME", DbType="VarChar(25)")]
		public string UNAME
		{
			get
			{
				return this._UNAME;
			}
			set
			{
				if ((this._UNAME != value))
				{
					this.OnUNAMEChanging(value);
					this.SendPropertyChanging();
					this._UNAME = value;
					this.SendPropertyChanged("UNAME");
					this.OnUNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXID", DbType="VarChar(13)")]
		public string TAXID
		{
			get
			{
				return this._TAXID;
			}
			set
			{
				if ((this._TAXID != value))
				{
					this.OnTAXIDChanging(value);
					this.SendPropertyChanging();
					this._TAXID = value;
					this.SendPropertyChanged("TAXID");
					this.OnTAXIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPALL", DbType="Char(1)")]
		public System.Nullable<char> SPALL
		{
			get
			{
				return this._SPALL;
			}
			set
			{
				if ((this._SPALL != value))
				{
					this.OnSPALLChanging(value);
					this.SendPropertyChanging();
					this._SPALL = value;
					this.SendPropertyChanged("SPALL");
					this.OnSPALLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LPREM", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> LPREM
		{
			get
			{
				return this._LPREM;
			}
			set
			{
				if ((this._LPREM != value))
				{
					this.OnLPREMChanging(value);
					this.SendPropertyChanging();
					this._LPREM = value;
					this.SendPropertyChanged("LPREM");
					this.OnLPREMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MGINT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> MGINT
		{
			get
			{
				return this._MGINT;
			}
			set
			{
				if ((this._MGINT != value))
				{
					this.OnMGINTChanging(value);
					this.SendPropertyChanging();
					this._MGINT = value;
					this.SendPropertyChanged("MGINT");
					this.OnMGINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAMT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> CHAMT
		{
			get
			{
				return this._CHAMT;
			}
			set
			{
				if ((this._CHAMT != value))
				{
					this.OnCHAMTChanging(value);
					this.SendPropertyChanging();
					this._CHAMT = value;
					this.SendPropertyChanged("CHAMT");
					this.OnCHAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHNO1", DbType="VarChar(2)")]
		public string CHNO1
		{
			get
			{
				return this._CHNO1;
			}
			set
			{
				if ((this._CHNO1 != value))
				{
					this.OnCHNO1Changing(value);
					this.SendPropertyChanging();
					this._CHNO1 = value;
					this.SendPropertyChanged("CHNO1");
					this.OnCHNO1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHNO2", DbType="VarChar(2)")]
		public string CHNO2
		{
			get
			{
				return this._CHNO2;
			}
			set
			{
				if ((this._CHNO2 != value))
				{
					this.OnCHNO2Changing(value);
					this.SendPropertyChanging();
					this._CHNO2 = value;
					this.SendPropertyChanged("CHNO2");
					this.OnCHNO2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHNO3", DbType="VarChar(2)")]
		public string CHNO3
		{
			get
			{
				return this._CHNO3;
			}
			set
			{
				if ((this._CHNO3 != value))
				{
					this.OnCHNO3Changing(value);
					this.SendPropertyChanging();
					this._CHNO3 = value;
					this.SendPropertyChanged("CHNO3");
					this.OnCHNO3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPINS", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> SPINS
		{
			get
			{
				return this._SPINS;
			}
			set
			{
				if ((this._SPINS != value))
				{
					this.OnSPINSChanging(value);
					this.SendPropertyChanging();
					this._SPINS = value;
					this.SendPropertyChanged("SPINS");
					this.OnSPINSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALLTY", DbType="VarChar(4)")]
		public string ALLTY
		{
			get
			{
				return this._ALLTY;
			}
			set
			{
				if ((this._ALLTY != value))
				{
					this.OnALLTYChanging(value);
					this.SendPropertyChanging();
					this._ALLTY = value;
					this.SendPropertyChanged("ALLTY");
					this.OnALLTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFINV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> MFINV
		{
			get
			{
				return this._MFINV;
			}
			set
			{
				if ((this._MFINV != value))
				{
					this.OnMFINVChanging(value);
					this.SendPropertyChanging();
					this._MFINV = value;
					this.SendPropertyChanged("MFINV");
					this.OnMFINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HACSH", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> HACSH
		{
			get
			{
				return this._HACSH;
			}
			set
			{
				if ((this._HACSH != value))
				{
					this.OnHACSHChanging(value);
					this.SendPropertyChanging();
					this._HACSH = value;
					this.SendPropertyChanged("HACSH");
					this.OnHACSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAHIR", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> HAHIR
		{
			get
			{
				return this._HAHIR;
			}
			set
			{
				if ((this._HAHIR != value))
				{
					this.OnHAHIRChanging(value);
					this.SendPropertyChanging();
					this._HAHIR = value;
					this.SendPropertyChanged("HAHIR");
					this.OnHAHIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PENSN", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> PENSN
		{
			get
			{
				return this._PENSN;
			}
			set
			{
				if ((this._PENSN != value))
				{
					this.OnPENSNChanging(value);
					this.SendPropertyChanging();
					this._PENSN = value;
					this.SendPropertyChanged("PENSN");
					this.OnPENSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LTEQF", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> LTEQF
		{
			get
			{
				return this._LTEQF;
			}
			set
			{
				if ((this._LTEQF != value))
				{
					this.OnLTEQFChanging(value);
					this.SendPropertyChanging();
					this._LTEQF = value;
					this.SendPropertyChanged("LTEQF");
					this.OnLTEQFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHEDU", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> CHEDU
		{
			get
			{
				return this._CHEDU;
			}
			set
			{
				if ((this._CHEDU != value))
				{
					this.OnCHEDUChanging(value);
					this.SendPropertyChanging();
					this._CHEDU = value;
					this.SendPropertyChanged("CHEDU");
					this.OnCHEDUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCNTR", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> FCNTR
		{
			get
			{
				return this._FCNTR;
			}
			set
			{
				if ((this._FCNTR != value))
				{
					this.OnFCNTRChanging(value);
					this.SendPropertyChanging();
					this._FCNTR = value;
					this.SendPropertyChanged("FCNTR");
					this.OnFCNTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MCNTR", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> MCNTR
		{
			get
			{
				return this._MCNTR;
			}
			set
			{
				if ((this._MCNTR != value))
				{
					this.OnMCNTRChanging(value);
					this.SendPropertyChanging();
					this._MCNTR = value;
					this.SendPropertyChanged("MCNTR");
					this.OnMCNTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFCTR", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> SFCTR
		{
			get
			{
				return this._SFCTR;
			}
			set
			{
				if ((this._SFCTR != value))
				{
					this.OnSFCTRChanging(value);
					this.SendPropertyChanging();
					this._SFCTR = value;
					this.SendPropertyChanged("SFCTR");
					this.OnSFCTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMCTR", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> SMCTR
		{
			get
			{
				return this._SMCTR;
			}
			set
			{
				if ((this._SMCTR != value))
				{
					this.OnSMCTRChanging(value);
					this.SendPropertyChanging();
					this._SMCTR = value;
					this.SendPropertyChanged("SMCTR");
					this.OnSMCTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPRCTR", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> SPRCTR
		{
			get
			{
				return this._SPRCTR;
			}
			set
			{
				if ((this._SPRCTR != value))
				{
					this.OnSPRCTRChanging(value);
					this.SendPropertyChanging();
					this._SPRCTR = value;
					this.SendPropertyChanged("SPRCTR");
					this.OnSPRCTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPRINS", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> FPRINS
		{
			get
			{
				return this._FPRINS;
			}
			set
			{
				if ((this._FPRINS != value))
				{
					this.OnFPRINSChanging(value);
					this.SendPropertyChanging();
					this._FPRINS = value;
					this.SendPropertyChanged("FPRINS");
					this.OnFPRINSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPRINS", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> MPRINS
		{
			get
			{
				return this._MPRINS;
			}
			set
			{
				if ((this._MPRINS != value))
				{
					this.OnMPRINSChanging(value);
					this.SendPropertyChanging();
					this._MPRINS = value;
					this.SendPropertyChanged("MPRINS");
					this.OnMPRINSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFPINS", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> SFPINS
		{
			get
			{
				return this._SFPINS;
			}
			set
			{
				if ((this._SFPINS != value))
				{
					this.OnSFPINSChanging(value);
					this.SendPropertyChanging();
					this._SFPINS = value;
					this.SendPropertyChanged("SFPINS");
					this.OnSFPINSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMPINS", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> SMPINS
		{
			get
			{
				return this._SMPINS;
			}
			set
			{
				if ((this._SMPINS != value))
				{
					this.OnSMPINSChanging(value);
					this.SendPropertyChanging();
					this._SMPINS = value;
					this.SendPropertyChanged("SMPINS");
					this.OnSMPINSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMMEXP", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> IMMEXP
		{
			get
			{
				return this._IMMEXP;
			}
			set
			{
				if ((this._IMMEXP != value))
				{
					this.OnIMMEXPChanging(value);
					this.SendPropertyChanging();
					this._IMMEXP = value;
					this.SendPropertyChanged("IMMEXP");
					this.OnIMMEXPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIALL", DbType="Char(1)")]
		public System.Nullable<char> DIALL
		{
			get
			{
				return this._DIALL;
			}
			set
			{
				if ((this._DIALL != value))
				{
					this.OnDIALLChanging(value);
					this.SendPropertyChanging();
					this._DIALL = value;
					this.SendPropertyChanged("DIALL");
					this.OnDIALLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DINO1", DbType="Char(1)")]
		public System.Nullable<char> DINO1
		{
			get
			{
				return this._DINO1;
			}
			set
			{
				if ((this._DINO1 != value))
				{
					this.OnDINO1Changing(value);
					this.SendPropertyChanging();
					this._DINO1 = value;
					this.SendPropertyChanged("DINO1");
					this.OnDINO1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_STATUS", DbType="Char(1)")]
		public System.Nullable<char> CHECK_STATUS
		{
			get
			{
				return this._CHECK_STATUS;
			}
			set
			{
				if ((this._CHECK_STATUS != value))
				{
					this.OnCHECK_STATUSChanging(value);
					this.SendPropertyChanging();
					this._CHECK_STATUS = value;
					this.SendPropertyChanged("CHECK_STATUS");
					this.OnCHECK_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CHECK_DATE
		{
			get
			{
				return this._CHECK_DATE;
			}
			set
			{
				if ((this._CHECK_DATE != value))
				{
					this.OnCHECK_DATEChanging(value);
					this.SendPropertyChanging();
					this._CHECK_DATE = value;
					this.SendPropertyChanged("CHECK_DATE");
					this.OnCHECK_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DB_News")]
	public partial class DB_New : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _New_ID;
		
		private string _New_Title;
		
		private string _New_Detail;
		
		private System.Nullable<System.DateTime> _New_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNew_IDChanging(int value);
    partial void OnNew_IDChanged();
    partial void OnNew_TitleChanging(string value);
    partial void OnNew_TitleChanged();
    partial void OnNew_DetailChanging(string value);
    partial void OnNew_DetailChanged();
    partial void OnNew_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnNew_DateChanged();
    #endregion
		
		public DB_New()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int New_ID
		{
			get
			{
				return this._New_ID;
			}
			set
			{
				if ((this._New_ID != value))
				{
					this.OnNew_IDChanging(value);
					this.SendPropertyChanging();
					this._New_ID = value;
					this.SendPropertyChanged("New_ID");
					this.OnNew_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_Title", DbType="NVarChar(MAX)")]
		public string New_Title
		{
			get
			{
				return this._New_Title;
			}
			set
			{
				if ((this._New_Title != value))
				{
					this.OnNew_TitleChanging(value);
					this.SendPropertyChanging();
					this._New_Title = value;
					this.SendPropertyChanged("New_Title");
					this.OnNew_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_Detail", DbType="NVarChar(MAX)")]
		public string New_Detail
		{
			get
			{
				return this._New_Detail;
			}
			set
			{
				if ((this._New_Detail != value))
				{
					this.OnNew_DetailChanging(value);
					this.SendPropertyChanging();
					this._New_Detail = value;
					this.SendPropertyChanged("New_Detail");
					this.OnNew_DetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> New_Date
		{
			get
			{
				return this._New_Date;
			}
			set
			{
				if ((this._New_Date != value))
				{
					this.OnNew_DateChanging(value);
					this.SendPropertyChanging();
					this._New_Date = value;
					this.SendPropertyChanged("New_Date");
					this.OnNew_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMPLOYEE_LOGIN")]
	public partial class EMPLOYEE_LOGIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _E_USERNAME;
		
		private string _E_PASSWORD;
		
		private int _E_NUM;
		
		private char _E_GRANT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_USERNAMEChanging(string value);
    partial void OnE_USERNAMEChanged();
    partial void OnE_PASSWORDChanging(string value);
    partial void OnE_PASSWORDChanged();
    partial void OnE_NUMChanging(int value);
    partial void OnE_NUMChanged();
    partial void OnE_GRANTChanging(char value);
    partial void OnE_GRANTChanged();
    #endregion
		
		public EMPLOYEE_LOGIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_USERNAME", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string E_USERNAME
		{
			get
			{
				return this._E_USERNAME;
			}
			set
			{
				if ((this._E_USERNAME != value))
				{
					this.OnE_USERNAMEChanging(value);
					this.SendPropertyChanging();
					this._E_USERNAME = value;
					this.SendPropertyChanged("E_USERNAME");
					this.OnE_USERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_PASSWORD", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string E_PASSWORD
		{
			get
			{
				return this._E_PASSWORD;
			}
			set
			{
				if ((this._E_PASSWORD != value))
				{
					this.OnE_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._E_PASSWORD = value;
					this.SendPropertyChanged("E_PASSWORD");
					this.OnE_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_NUM", DbType="Int NOT NULL")]
		public int E_NUM
		{
			get
			{
				return this._E_NUM;
			}
			set
			{
				if ((this._E_NUM != value))
				{
					this.OnE_NUMChanging(value);
					this.SendPropertyChanging();
					this._E_NUM = value;
					this.SendPropertyChanged("E_NUM");
					this.OnE_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_GRANT", DbType="Char(1) NOT NULL")]
		public char E_GRANT
		{
			get
			{
				return this._E_GRANT;
			}
			set
			{
				if ((this._E_GRANT != value))
				{
					this.OnE_GRANTChanging(value);
					this.SendPropertyChanging();
					this._E_GRANT = value;
					this.SendPropertyChanged("E_GRANT");
					this.OnE_GRANTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DB_FAQ")]
	public partial class DB_FAQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Q_ID;
		
		private string _Question;
		
		private string _Answer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQ_IDChanging(int value);
    partial void OnQ_IDChanged();
    partial void OnQuestionChanging(string value);
    partial void OnQuestionChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    #endregion
		
		public DB_FAQ()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Q_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Q_ID
		{
			get
			{
				return this._Q_ID;
			}
			set
			{
				if ((this._Q_ID != value))
				{
					this.OnQ_IDChanging(value);
					this.SendPropertyChanging();
					this._Q_ID = value;
					this.SendPropertyChanged("Q_ID");
					this.OnQ_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(MAX)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this.OnQuestionChanging(value);
					this.SendPropertyChanging();
					this._Question = value;
					this.SendPropertyChanged("Question");
					this.OnQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(MAX)")]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaxEdit_List")]
	public partial class TaxEdit_List : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _No;
		
		private string _ID;
		
		private string _Data_Type;
		
		private string _Old_Value;
		
		private string _New_Value;
		
		private System.Nullable<System.DateTime> _Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoChanging(int value);
    partial void OnNoChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnData_TypeChanging(string value);
    partial void OnData_TypeChanged();
    partial void OnOld_ValueChanging(string value);
    partial void OnOld_ValueChanged();
    partial void OnNew_ValueChanging(string value);
    partial void OnNew_ValueChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    #endregion
		
		public TaxEdit_List()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(8)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Type", DbType="VarChar(10)")]
		public string Data_Type
		{
			get
			{
				return this._Data_Type;
			}
			set
			{
				if ((this._Data_Type != value))
				{
					this.OnData_TypeChanging(value);
					this.SendPropertyChanging();
					this._Data_Type = value;
					this.SendPropertyChanged("Data_Type");
					this.OnData_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Old_Value", DbType="VarChar(12)")]
		public string Old_Value
		{
			get
			{
				return this._Old_Value;
			}
			set
			{
				if ((this._Old_Value != value))
				{
					this.OnOld_ValueChanging(value);
					this.SendPropertyChanging();
					this._Old_Value = value;
					this.SendPropertyChanged("Old_Value");
					this.OnOld_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_Value", DbType="VarChar(12)")]
		public string New_Value
		{
			get
			{
				return this._New_Value;
			}
			set
			{
				if ((this._New_Value != value))
				{
					this.OnNew_ValueChanging(value);
					this.SendPropertyChanging();
					this._New_Value = value;
					this.SendPropertyChanged("New_Value");
					this.OnNew_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
