<?xml version="1.0" encoding="utf-8"?><Database Name="hrdb" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.30.7.163;Initial Catalog=hrdb;User ID=hradmin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="hrdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EMPLOYEE_INFO" Member="EMPLOYEE_INFOs">
    <Type Name="EMPLOYEE_INFO">
      <Column Name="E_ID" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_TITLE_TYPE" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="E_TITLE" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="E_TITLE_DESC" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="E_TITLE_FULL_DESC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="E_TITLE1" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="E_TITLE1_DESC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="E_TITLE2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="E_TITLE2_DESC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="E_TITLE3" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="E_TITLE3_DESC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="E_TITLE4" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="E_TITLE4_DESC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="E_NAMEF" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="E_NAMEL" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="E_PERM_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_BIRTH_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_ENTRY_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_POSI_ST" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="E_POS_ST_DESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="E_POSI_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_STAFF_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_RELIGION" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="E_RELG_NAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="E_RACE" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="RACE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="E_NATIONALITY" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="NATIONALITY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="E_MARITAL_ST" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="E_MARITAL_ST_DESC" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="E_SEX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="E_SEX_DESC" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="E_POSI_CODE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="E_POST_TEXT_SHORT" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="E_POST_TEXT" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="E_LEVEL_CODE" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="E_LEVEL_DESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DEPT_STABLE_CODE" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="DEPT_CHANGE_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DEPT_SHORT" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="DEPT_FULL" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="E_RETIRED" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_EMP_ST" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="E_EMP_ST_DESC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="E_UPD_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_RETIRED2_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_QUALIF" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="E_QUALIF_DESC" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="E_QUALIF_LEVEL" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="E_QUALIF_LEVEL_DESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="E_DEPT" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="E_DEPT_DESC" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="E_BLOOD_GROUP" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="E_IDENTITY_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="E_DEPT_SAP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="E_DEPT_SHORT" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="E_DEPT_FULL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="E_REG" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="E_REG_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="E_SUB_REG" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="E_SUB_REG_NAME" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="E_COST_CENTER" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="E_COST_CENTER_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="E_BA" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="E_BA_NAME" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="E_PY_AREA" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="E_PY_AREA_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="E_VENDOR_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="E_BEG_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_CONT_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="E_END_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAX_Desc" Member="TAX_Descs">
    <Type Name="TAX_Desc">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PA0364" Member="PA0364s">
    <Type Name="PA0364">
      <Column Name="PERNR" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ENDDA" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BEGDA" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AEDTM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UNAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="TAXID" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="SPALL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LPREM" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="MGINT" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="CHAMT" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="CHNO1" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CHNO2" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CHNO3" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="SPINS" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="ALLTY" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="MFINV" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="HACSH" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="HAHIR" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="PENSN" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="LTEQF" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="CHEDU" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="FCNTR" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="MCNTR" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="SFCTR" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="SMCTR" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="SPRCTR" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="FPRINS" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="MPRINS" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="SFPINS" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="SMPINS" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="IMMEXP" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="DIALL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DINO1" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CHECK_STATUS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CHECK_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_News" Member="DB_News">
    <Type Name="DB_New">
      <Column Name="New_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="New_Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_Detail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="New_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMPLOYEE_LOGIN" Member="EMPLOYEE_LOGINs">
    <Type Name="EMPLOYEE_LOGIN">
      <Column Name="E_USERNAME" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_PASSWORD" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_NUM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="E_GRANT" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DB_FAQ" Member="DB_FAQs">
    <Type Name="DB_FAQ">
      <Column Name="Q_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaxEdit_List" Member="TaxEdit_Lists">
    <Type Name="TaxEdit_List">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Data_Type" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Old_Value" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="New_Value" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>